<!-- toggle sidebar on mobile size screen -->
<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
    <a class="navbar-brand me-lg-5" href="<?= base_url('dashboard') ?>">
        <img class="navbar-brand-dark" src="<?= base_url('assets/images/') ?>ntbprov.webp" alt="Logo" /> <img class="navbar-brand-light" src="<?= base_url('assets/images/') ?>ntbprov.webp" alt="WEBGIS FASILITAS JALAN" />
    </a>
    <div class="d-flex align-items-center">
        <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>
<style>
    .sidebar .nav-link {
        font-size: 0.85rem; /* default sekitar 1rem, jadi ini dikecilkan */
    }

    .sidebar .nav-link span {
        font-size: 0.85rem;
    }

    .sidebar span.sidebar-brand-text {
        font-size: 1rem; /* atau lebih kecil seperti 0.75rem */
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        display: inline-block;
        max-width: 160px; /* Batasi agar tidak menyebabkan scroll horizontal */
    }

</style>
<!-- sidebar -->
<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
    <div class="sidebar-inner px-4 pt-3">
        <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
            <div class="d-flex align-items-center">
                <div class="avatar-lg me-4">
                <!-- <img src="<?= base_url() ?>assets/images/user.png" class="card-img-top rounded-circle border-white"
                    alt="Bonnie Green"> -->
                <i class="far fa-user-circle text-muted"></i>
                </div>
                <div class="d-block">
                <h2 class="h5 mb-3">Hi, <?= session('nama') ?></h2>
                <a href="<?= site_url('logout') ?>" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
                    <i class="fas fa-arrow-right-from-bracket"></i>
                    Logout
                </a>
                </div>
            </div>
            <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" data-bs-toggle="collapse"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
                    aria-label="Toggle navigation">
                    <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                </a>
            </div>
        </div>
        <ul class="nav flex-column pt-3 pt-md-0">
            <li class="nav-item">
                <a href="<?= base_url('dashboard') ?>" class="nav-link d-flex align-items-center">
                    <span class="sidebar-icon">
                        <img src="<?= base_url('assets/images/') ?>ntbprov.webp" height="30" alt="WEBGIS FASILITAS JALAN">
                    </span>
                    <span class="mt-1 ms-1 sidebar-brand-text">WEBGIS</span>
                </a>
            </li>
            <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
            <div id="sidebar-menu">
                <!-- generated by ajax -->
                <li class="nav-item">
                    <a href="<?= base_url() ?>/dashboard" class="nav-link">
                        <span class="sidebar-icon"><i class="fas fa-dashboard me-2"></i></span>
                        <span class="sidebar-text">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item">
                    <span class="nav-link collapsed d-flex justify-content-between align-items-center" data-bs-toggle="collapse" data-bs-target="#menuJenisFasilitas">
                        <span>
                            <span class="sidebar-icon"><i class="fas fa-tags me-2"></i></span>
                            <span class="sidebar-text">Jenis Fasilitas</span>
                        </span>
                        <span class="link-arrow">
                            <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
                            </svg>
                        </span>
                    </span>
                    <div class="multi-level collapse" id="menuJenisFasilitas">
                        <ul class="flex-column nav">
                            <li class="nav-item">
                                <a class="nav-link" href="<?= site_url() ?>/jenis-fasilitas">
                                    <span class="sidebar-text" id="submenu-fasilitasIndex">Daftar</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <span class="nav-link collapsed d-flex justify-content-between align-items-center" data-bs-toggle="collapse" data-bs-target="#menuFasilitas">
                        <span>
                            <span class="sidebar-icon"><i class="fas fa-road me-2"></i></span>
                            <span class="sidebar-text">Fasilitas</span>
                        </span>
                        <span class="link-arrow">
                            <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
                            </svg>
                        </span>
                    </span>
                    <div class="multi-level collapse" id="menuFasilitas">
                        <ul class="flex-column nav">
                            <li class="nav-item">
                                <a class="nav-link" href="<?= site_url() ?>/fasilitas">
                                    <span class="sidebar-text" id="submenu-fasilitasIndex">Daftar</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= site_url() ?>/fasilitas/add">
                                    <span class="sidebar-text" id="submenu-fasilitasAdd">Tambah Data</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                
                <li class="nav-item">
                    <span class="nav-link collapsed d-flex justify-content-between align-items-center" data-bs-toggle="collapse" data-bs-target="#menuRencana">
                        <span>
                            <span class="sidebar-icon"><i class="fas fa-sliders me-2"></i></span>
                            <span class="sidebar-text">Rencana</span>
                        </span>
                        <span class="link-arrow">
                            <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
                            </svg>
                        </span>
                    </span>
                    <div class="multi-level collapse" id="menuRencana">
                        <ul class="flex-column nav">
                            <li class="nav-item">
                                <a class="nav-link" href="<?= site_url() ?>/users">
                                    <span class="sidebar-text" id="submenu-pengguna">Pengguna</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= site_url() ?>/database">
                                    <span class="sidebar-text" id="submenu-database">Database</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                
                <li class="nav-item">
                    <span class="nav-link collapsed d-flex justify-content-between align-items-center" data-bs-toggle="collapse" data-bs-target="#menuSettings">
                        <span>
                            <span class="sidebar-icon"><i class="fas fa-gears me-2"></i></span>
                            <span class="sidebar-text">Pengaturan</span>
                        </span>
                        <span class="link-arrow">
                            <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
                            </svg>
                        </span>
                    </span>
                    <div class="multi-level collapse" id="menuSettings">
                        <ul class="flex-column nav">
                            <li class="nav-item">
                                <a class="nav-link" href="<?= site_url() ?>/users">
                                    <span class="sidebar-text" id="submenu-pengguna">Pengguna</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= site_url() ?>/database">
                                    <span class="sidebar-text" id="submenu-database">Database</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a href="<?= base_url() ?>/reports" class="nav-link">
                        <span class="sidebar-icon"><i class="fas fa-briefcase me-2"></i></span>
                        <span class="sidebar-text">Laporan</span>
                    </a>
                </li>
            </div>

            

            <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
            
            <li class="nav-item">
                <a class="btn btn-danger d-flex align-items-center justify-content-center btn-upgrade-pro" href="<?= site_url('logout') ?>">
                    <span class="sidebar-icon d-inline-flex align-items-center justify-content-center">
                        <i class="fas fa-arrow-right-from-bracket"></i> Logout
                    </span>
                </a>
            </li>
        </ul>
    </div>
</nav>

<!-- render sidebar -->
<script>

</script>
