<!-- toggle sidebar on mobile size screen -->
<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
    <a class="navbar-brand me-lg-5" href="<?= base_url('dashboard') ?>">
        <img class="navbar-brand-dark" src="<?= base_url('assets/images/') ?>logo_mataram.png" alt="Volt logo" /> <img class="navbar-brand-light" src="<?= base_url('assets/images/') ?>logo_mataram.png" alt="POLITEKNIK DUKCAPIL" />
    </a>
    <div class="d-flex align-items-center">
        <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>
<style>
    .sidebar .nav-link {
        font-size: 0.85rem; /* default sekitar 1rem, jadi ini dikecilkan */
    }

    .sidebar .nav-link span {
        font-size: 0.85rem;
    }

    .sidebar span.sidebar-brand-text {
        font-size: 1rem; /* atau lebih kecil seperti 0.75rem */
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        display: inline-block;
        max-width: 160px; /* Batasi agar tidak menyebabkan scroll horizontal */
    }

</style>
<!-- sidebar -->
<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
    <div class="sidebar-inner px-4 pt-3">
        <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
            <div class="d-flex align-items-center">
                <div class="avatar-lg me-4">
                <img src="<?= base_url() ?>assets/images/user.png" class="card-img-top rounded-circle border-white"
                    alt="Bonnie Green">
                </div>
                <div class="d-block">
                <h2 class="h5 mb-3">Hi, <?= session('nama') ?></h2>
                <a href="<?= site_url('logout') ?>" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
                    <i class="fas fa-arrow-right-from-bracket"></i>
                    Logout
                </a>
                </div>
            </div>
            <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" data-bs-toggle="collapse"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
                    aria-label="Toggle navigation">
                    <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                </a>
            </div>
        </div>
        <ul class="nav flex-column pt-3 pt-md-0">
            <li class="nav-item">
                <a href="<?= base_url('dashboard') ?>" class="nav-link d-flex align-items-center">
                    <span class="sidebar-icon">
                        <img src="<?= base_url('assets/images/') ?>logo_mataram.png" height="30" width="30" alt="POLITEKNIK DUKCAPIL">
                    </span>
                    <span class="mt-1 ms-1 sidebar-brand-text"><img src="<?= base_url('assets/images/') ?>logo.png" alt="POLITEKNIK DUKCAPIL"></span>
                </a>
            </li>
            <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
            <div id="sidebar-menu">
                <!-- generated by ajax -->
            </div>

            <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>
            
            <li class="nav-item">
                <a class="btn btn-danger d-flex align-items-center justify-content-center btn-upgrade-pro" href="<?= site_url('logout') ?>">
                    <span class="sidebar-icon d-inline-flex align-items-center justify-content-center">
                        <i class="fas fa-arrow-right-from-bracket"></i> Logout
                    </span>
                </a>
            </li>
        </ul>
    </div>
</nav>

<!-- render sidebar -->
<script>
$(document).ready(function () {
    getSidebarMenu();
    getTotalNotif();
});

function getTotalNotif(){
    $.ajax({
        url: `<?= site_url('notifikasi') ?>`,
        type: 'GET',
        data: {
            status: 'pengajuan'
        },
        dataType: 'JSON',
        success: (res) => {
            let data = res.data;
            $('#submenu-verif-kk').append(` <sup><span class="badge bg-danger rounded-pill">${data.kk}</span></sup>`);
            $('#submenu-verif-akta-lahir').append(` <sup><span class="badge bg-danger rounded-pill">${data.akta_lahir}</span></sup>`);
            $('#submenu-verif-akta-mati').append(` <sup><span class="badge bg-danger rounded-pill">${data.akta_mati}</span></sup>`);
            $('#submenu-verif-surat-pindah').append(` <sup><span class="badge bg-danger rounded-pill">${data.surat_pindah}</span></sup>`);
            $(".sidebar-text:contains('Verifikasi')").append(` <sup><span class="badge bg-danger rounded-pill">${data.total}</span></sup>`);
        },
        error: (err) => {
            console.log(err.responseJSON);
        }
    });
}

function getSidebarMenu() {
    $.ajax({
        url: '<?= site_url('sidebar') ?>',
        type: 'GET',
        dataType: 'json',
        success: function (res) {
            if (res.status && res.data) {
                renderSidebarMenu(res.data);
            } else {
                console.warn('Menu kosong atau gagal diambil.');
            }
        },
        error: function (xhr, status, error) {
            console.error('Gagal mengambil sidebar:', status, error);
        }
    });
}

function renderSidebarMenu(data) {
    let menuHtml = '';

    data.forEach(menu => {
        if (menu.children && menu.children.length > 0) {
            // Menu dengan sub-menu
            const submenuId = `submenu-${menu.id}`;
            menuHtml += `
                <li class="nav-item">
                    <span class="nav-link collapsed d-flex justify-content-between align-items-center" data-bs-toggle="collapse" data-bs-target="#${submenuId}">
                        <span>
                            <span class="sidebar-icon"><i class="${menu.icon} me-2"></i></span>
                            <span class="sidebar-text">${menu.name}</span>
                        </span>
                        <span class="link-arrow">
                            <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
                            </svg>
                        </span>
                    </span>
                    <div class="multi-level collapse" id="${submenuId}">
                        <ul class="flex-column nav">
                            ${menu.children.map(child => `
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= base_url() ?>${child.url}">
                                        <span class="sidebar-text" id="submenu-${child.url}">${child.name}</span>
                                    </a>
                                </li>
                            `).join('')}
                        </ul>
                    </div>
                </li>
            `;
        } else if(menu.url !== null || menu.children.length > 0) {
            // Menu tanpa sub-menu
            menuHtml += `
                <li class="nav-item">
                    <a href="<?= base_url() ?>${menu.url}" class="nav-link">
                        <span class="sidebar-icon"><i class="${menu.icon} me-2"></i></span>
                        <span class="sidebar-text">${menu.name}</span>
                    </a>
                </li>
            `;
        }
    });
    $('#sidebar-menu').html(menuHtml);
    highlightActiveMenu();
}

function highlightActiveMenu() {
    const currentUrl = window.location.pathname.replace(/^\/+|\/+$/g, ''); // tanpa slash awal/akhir

    $('#sidebar-menu a.nav-link').each(function () {
        const linkUrl = $(this).attr('href').replace(/^\/+|\/+$/g, '').replace('<?= base_url() ?>', '');

        if (currentUrl === linkUrl) {
            $(this).addClass('active');

            // Buka parent collapse jika submenu
            const parentCollapse = $(this).closest('.collapse');
            if (parentCollapse.length) {
                parentCollapse.addClass('show'); // buka submenu
                const parentToggle = parentCollapse.siblings('[data-bs-toggle="collapse"]');
                parentToggle.removeClass('collapsed');
            }
        }
    });
}
</script>
